"""add winner_place to customers

Revision ID: 81d69a19e197
Revises: 97d55a4cd613
Create Date: 2025-12-19 09:06:49.113408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d69a19e197'
down_revision: Union[str, Sequence[str], None] = '97d55a4cd613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('winner_place', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'winner_place')
    # ### end Alembic commands ###
