"""add_notification_tracking

Revision ID: 94002473cfff
Revises: 81d69a19e197
Create Date: 2025-12-19 10:12:28.718907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94002473cfff'
down_revision: Union[str, Sequence[str], None] = '81d69a19e197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_notified', sa.Boolean(), nullable=True))
    op.execute("UPDATE customers SET is_notified = FALSE")
    op.alter_column('customers', 'is_notified', nullable=False)
    op.add_column('customers', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'notified_at')
    op.drop_column('customers', 'is_notified')
    # ### end Alembic commands ###
